// Auto-generated by scripts/update-frontend-addresses.js — do not edit by hand
// Source: ignition/deployments/chain-31337/deployed_addresses.json

export const STAKING_ADDRESS = "0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9";
export const TOKEN_ADDRESS   = "0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0";

export const HARDHAT_CHAIN_ID = 31337;
