// Auto-generated by scripts/update-frontend-addresses.js — do not edit by hand
// Source: ignition/deployments/chain-31337/deployed_addresses.json

export const STAKING_ADDRESS = "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512";
export const TOKEN_ADDRESS   = "0x5FbDB2315678afecb367f032d93F642f64180aa3";

export const HARDHAT_CHAIN_ID = 31337;
