// Human-readable ABI for ArkenstoneStaking (interest in bps, TVL, Graph-ready events)
const ABI = [
  "function deposit() payable",
  "function withdraw(uint256 amount)",
  "function claimRewards()",
  "function claimAllRewards()",
  "function getPendingRewards(address user) view returns (uint256)",
  "function getStakeInfo(address user) view returns (uint256 stakedAmount, uint256 pendingRewards, uint256 lastUpdateTime)",
  "function interestRateBps() view returns (uint256)",
  "function arknInterestRateBps() view returns (uint256)",
  "function setInterestRateBps(uint256 bps)",
  "function setArknInterestRateBps(uint256 bps)",
  "function owner() view returns (address)",
  "function depositArkn(uint256 amount)",
  "function withdrawArkn(uint256 amount)",
  "function claimArknRewards()",
  "function getArknStakeInfo(address user) view returns (uint256 stakedAmount, uint256 pendingRewards, uint256 lastUpdateTime)",
  "function getPendingArknRewards(address user) view returns (uint256)",
  "function getTVL() view returns (uint256 totalEth, uint256 totalArkn)",
  "function totalEthStaked() view returns (uint256)",
  "function totalArknStaked() view returns (uint256)",
  "event Deposited(address indexed user, uint256 amount)",
  "event Withdrawn(address indexed user, uint256 amount)",
  "event RewardsClaimed(address indexed user, uint256 amount)",
  "event InterestRateUpdated(uint256 oldBps, uint256 newBps)",
  "event ArknDeposited(address indexed user, uint256 amount)",
  "event ArknWithdrawn(address indexed user, uint256 amount)",
  "event ArknRewardsClaimed(address indexed user, uint256 amount)",
  "event ArknInterestRateUpdated(uint256 oldBps, uint256 newBps)",
];

export default ABI;
